### ISSUE TITLE
Question on Custom Query/Selector

### ISSUE THREAD

**Issue by frank1340** [matteodem/meteor-easy-search#143]
Hello, relatively new to Javascript.

I don't quite understand the custom query selector concept.  

I have multiple fields to search on.  I want to return documents if there is a match in one field or through both fields.  For example:

Type in "head case"
Field one contains: "head down"
Field two contains: "case closed"

I would want to match based on this, returning the document containing the fields above, but with the default selector, this document is not returned.

This is likely an easy thing to fix, but looking at the examples, I don't quite see how.  Again, I am a JS neophyte.

Thanks.

**Comment by matteodem** [comment]
Hey there

Currently it is not possible with MongoDB, since 2.4 doesn't "officialy" support text indexes. As soon as 2.6 is shipped with Meteor you can use it for searching. Right now you'd probably have to use Elastic Search or implement a Searcher with the Public API.

http://matteodem.github.io/meteor-easy-search/docs/search-engines/

**Comment by frank1340** [comment]
Thanks for the reply.

Rather than that, how would I pare down the search?  For example, add a field called "type" to all documents which I could search within based on what the user clicked on, within the same collection.

**Comment by frank1340** [comment]
I believe I figured this out.  I'm still not sure of the JS, but I can make it work.  Thank you.

**Comment by matteodem** [comment]
Feel free to ask if you still got questions and I'll re-open the ticket
