### ISSUE TITLE
Add possibility to weight fields (MongoDB text indexes) 

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#197]
See http://docs.mongodb.org/manual/tutorial/control-results-of-text-search/.

**Comment by matteodem** [comment]
Have a look at the new ```weights``` property: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/

**Comment by huevoncito** [comment]
@matteodem This isn't working for me. I'm getting `options is not defined` at `packages/easysearch:core/lib/engines/mongo-text-index.js:34:26`. It's tough to tell from looking at the code, but is it possible that instead of `textIndexesConfig.weights = options.weights()` you mean `textIndexConfig.weights = indexConfig.weights`?
