### ISSUE TITLE
Searching by multiple fields

### ISSUE THREAD

**Issue by mikkhait** [matteodem/meteor-easy-search#223]
Is there a way to do that?

See in detail at StackOverflow http://stackoverflow.com/questions/30496210/searching-by-multiple-fields-using-meteor-easy-search

**Comment by ricardodovalle** [comment]
:+1:

**Comment by juvyinparallel** [comment]
My question is very similar. I want to search over entries that have ALL words from the search string in the object. for example

search string - > "A B C"

{
name: "A",
category: "B",
subcategory: "C"
}

{
name: "A",
category: "D",
subcategory: "C"
}

This feature would only bring up the first entry. 

I tried using 'useTextIndexes': true
But that returns entries with ANY of the words from the search string.

Any guidance would be much appreciated.

**Comment by matteodem** [comment]
The way I would do it right now is by having one input field be the main search (as an `esInput`) and the other one be an input field where you have a custom event that acts on keyup and does something like this:

```javascript
Template.test.events({
  'keyup .second-input': function (e) {
    EasySearch.changeProperty('yourIndex', 'location', $(e.target).val().trim());
    EasySearch.getComponentInstance(...).triggerSearch();
  }
});
```

This will trigger the search and you can then act on the different location in your custom `query` method, see http://matteodem.github.io/meteor-easy-search/docs/javascript-api/.

I'll create a new issue for this though, since the feature is not implemented.

**Comment by matteodem** [comment]
This is now possible as of v2, with the [EasySearch.FieldInput](http://matteodem.github.io/meteor-easy-search/docs/components/) component.
