### ISSUE TITLE
Manually setting esInput value

### ISSUE THREAD

**Issue by Akheos** [matteodem/meteor-easy-search#237]
Hi Matteodem,

First of all, thanks for this great & easy to use package :)

I'm a bit ashamed to ask such a simple question here, but I struggle with manually setting the value of the esInput field via Javascript.
The esInput component does not support the value property, so I can't use a helper.

Is there a way, once we have the instance (through EasySearch.getComponentInstance), to set the value which will appear in the search field?

Thanks and have a great day!

**Comment by matteodem** [comment]
It is only possible with a workaround right now, but I'll merge #235 soon.

The way you could do it right now until the new version is out, is by setting the value with jquery.

**Comment by Akheos** [comment]
Hi !

Thanks a lot for your fast answer :)
I hadn't seen the 235 thread, sorry.

Ok I'll use Jquery in the meantime! 

Have a good day

**Comment by artitw** [comment]
I tried to use JQuery, but ran into some issues. See 
https://github.com/matteodem/meteor-easy-search/issues/242

**Comment by Akheos** [comment]
But then it works if we manually trigger the search with
esInput.search("some query");
And then we can use jquery in the rendered template to set the value to the
query (and the focus), and then it works perfectly :)

Thanks!

**Comment by artitw** [comment]
Where do I get `esInput.search()`? Can you provide me with the example or documentation? Thanks!

**Comment by matteodem** [comment]
see http://matteodem.github.io/meteor-easy-search/docs/component-api/

**Comment by matteodem** [comment]
You can set a default value now http://matteodem.github.io/meteor-easy-search/docs/blaze-components/

**Comment by Akheos** [comment]
Thanks a lot for the feedback ;)
Great work!

**Comment by HadenHiles** [comment]
What would be the best way to do this when the value I want to set needs to be reactive?

I have a Session variable named "SearchTerm" and before implementing the EasySearch.Input I would do something like this: `<input type="text" name="search" value="{{theSearchTerm}}"`

Where `{{theSearchTerm}}` is a helper function that returns `Session.get('SearchTerm');`

But I can't seem to figure out a way to do this using `{{> EasySearch.Input index=searchIndex}}`. I even tried passing the `Session.get('SearchTerm')` directly to the attributes parameter like so: 

    //In the template
    {{> EasySearch.Input ... attributes=inputAttributes }}
    
    // And the inputAttributes helper
    inputAttributes: function () {
        return { ... value: Session.get('searchTerm') };
    }

but had no luck.

My reason for needing this is that I have two inputs who's values need to be in sync so that  a search can be triggered from either input. I realize that I could just use a keyup event and update the value with jQuery but I feel as if there should be a more "Meteor Way" of doing it.

Any help is appreciated :)

**Comment by matteodem** [comment]
There are component methods, that allow you to search on the input. see http://matteodem.github.io/meteor-easy-search/docs/components/

**Comment by matteodem** [comment]
there's also a recipe here http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by HadenHiles** [comment]
I actually did find those, as it turns out my `Session.set("SearchTerm")` was actually `Session.set("searchTerm")` -_- sorry for the inconvenience.

Oh and just FYI, this works reactively:

    inputAttributes: function () {
        return { ... value: Session.get('searchTerm') };
    }

Thanks!
