### ISSUE TITLE
Search query being added to end of id

### ISSUE THREAD

**Issue by holwech** [matteodem/meteor-easy-search#347]
Hi!

I'm experiencing a problem where the search query is added to end the of all the id's.

When there is nothing in the input box, it's just adds an empty "" at the end of id
![screenshot from 2015-10-31 11-58-37](https://cloud.githubusercontent.com/assets/7474295/10863327/ccb37854-7fc9-11e5-8916-8aafe3ad0524.png)

And if there is any input, it gets inserted inside the quotation marks.
![screenshot from 2015-10-31 11-59-19](https://cloud.githubusercontent.com/assets/7474295/10863337/5f565140-7fca-11e5-8cbd-2248abfbdf64.png)

I could well be a issue with my code, but I'm not sure why it is happening or how to fix it.

Relevant code:
client/searchResult.js
```javascript
Template.searchResult.helpers({
  wordsIndex: () => WordsIndex
});
```
client/searchResult.html
```html
<template name="searchResult">
  {{> EasySearch.Input index=wordsIndex}}

  <ul>
    {{#EasySearch.Each index=wordsIndex}}
      <li>{{word}} - {{_id}}</li>
    {{/EasySearch.Each}}
  </ul>

  {{> EasySearch.LoadMore index=wordsIndex}}

  {{#EasySearch.IfNoResults index=wordsIndex}}
    <div class="no-results">No results found!</div>
  {{/EasySearch.IfNoResults}}
</template>
```
common/collections.js
```javascript
Words =  new Mongo.Collection("words");
WordsIndex = new EasySearch.Index({
  collection: Words,
  fields: ['word'],
  engine: new EasySearch.MongoDB()
});
```

**Comment by carnec** [comment]
Hi,

Ran into the same "issue" yesterday, it turns out you should use _originalId as the [doc](http://matteodem.github.io/meteor-easy-search/docs/recipes/) says :
>EasySearch returns documents when using search that have the same fields as the original ones, but the _id is different. If you want to perform changes on search result documents by the id you can use the __originalId which contains the original _id of the document. So collection.findOne(doc._id) won't work, while collection.findOne(doc.__originalId) would.

The search-appended _id is probably used internally by this package

**Comment by holwech** [comment]
That solved it. Thank you very much!

**Comment by matteodem** [comment]
Yes exactly, sorry for the confusion. Not sure how to make this more "obvious", I'll read again through the docs and add some statements that it creates new "documents" on the client.

**Comment by joaobarcia** [comment]
Hi @matteodem , 

Thanks a lot for version 2! It brings many improvements which are really handy for us.

Regarding _originalId vs _id there a strong reason for it to work like this?

In our specific use case it will increase complexity considerably. We have a template which displays info about our pages info in a collection item (http://materializecss.com/collections.html). We use this templates in various situations and one of them is the search results.

If we have to use create a new template just for the search, we will be creating redundant code and have to keep 2 versions just because _id is not accepted.

**Comment by carnec** [comment]
Can't you register a global helper that returns _originalId when the property exists and _id otherwise?

Or even directly in the template use {{#unless _originalId}} ?

**Comment by matteodem** [comment]
There should be a way as @carnec suggested to abstract that logic, because somewhere it's defined that _id is used by default, right? Feel free to create a new issue if it's a question of how to abstract the code.

**Comment by joaobarcia** [comment]
For the moment we are passing an _id=__originalId as a template argument when we are calling our collection items template, but thanks for the suggestions.

**Comment by streamnsight** [comment]
ran into this also today...
this is very confusing.

is there a technical reason the internal logic can't use its own _id and leave the original _id alone?

**Comment by matteodem** [comment]
The main problem is sorting. Since the same document can be in multiple search results it's hard to have a consistent way (in one document) with how to deal with different sortings and methods such as `beforePublish` where the same document can potentially have different fields based on defined filters / props complicates this even more.

Also it's not possible to do most of these things on the client side, since sorting for `textScore` wouldn't work on the client (see https://docs.mongodb.org/v3.0/reference/operator/projection/meta/).

**Comment by CarnivorousRex** [comment]
With all of this, how does one update a collection to the server when _id has been altered on the client side?  The search functionality is great, but I'm having a devil of a time getting view counts and up votes to tally.  Any ideas?

**Comment by matteodem** [comment]
Did you see the answer provided by @carnec?
