### ISSUE TITLE
Permissions error message on user logout

### ISSUE THREAD

**Issue by Skulmuk** [matteodem/meteor-easy-search#388]
Is there a recommended way to ignore the permissions check if a user logs out? It's not breaking anything but it does leave an **not-allowed** error in the console which looks bad to non-developers. Is it as simple as returning true if the current user ID is null?

**Comment by mbreuer23** [comment]
That's one way, but it really depends on your use case.  If you do that, a logged out user could theoretically still search the index using the javascript console. If you're okay with that (maybe because the search is defined in such a way to show only docs belonging to the current user, in which case no docs would be returned when a user is logged out) then your method should work.

**Comment by matteodem** [comment]
Do you know why a search is being triggered on logout?

**Comment by matteodem** [comment]
Any progress on this? Feel free to write into the issue and I'll reopen it.
